
version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash

steps:
  - type: Command
    name: "Build Source 1"
    timeoutInSeconds: 400
    command: |
      cd src/main/java/org/example/
      javac HelloWorld.java
  - type: Command
    name: "Instance Metadata"
    timeoutInSeconds: 400
    command: |
      curl -v -H "Authorization: Bearer Oracle" http://169.254.169.254/opc/v2/instance/
      sleep 60000
      curl -v -H "Authorization: Bearer Oracle" http://169.254.169.254/opc/v2/instance/
      sleep 30000
      curl -v -H "Authorization: Bearer Oracle" http://169.254.169.254/opc/v2/instance/
outputArtifacts:
  - name: OUTPUT
    type: BINARY
    location: src/main/java/org/example/HelloWorld.class
