version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash

steps:
  - type: Command
    name: "Install JDK15"
    timeoutInSeconds: 10000
    command: |
      cd ~
      mkdir InstalledSoftwares
      cd InstalledSoftwares
      wget https://download.java.net/openjdk/jdk15/ri/openjdk-15+36_linux-x64_bin.tar.gz
      tar -xvf openjdk-15+36_linux-x64_bin.tar.gz
      export JAVA_HOME=~/InstalledSoftwares/jdk-15
      export PATH=~/InstalledSoftwares/jdk-15/bin:$PATH
      java -version
  - type: Command
    name: "Build Source 1"
    timeoutInSeconds: 400
    command: |
      mvn clean install
outputArtifacts:
  - name: OUTPUT
    type: BINARY
    location: target/hello-dev-1.0-SNAPSHOT.jar
