version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  exportedVariables:
    - var

steps:
  - type: Command
    name: "Github Build Source"
    timeoutInSeconds: 400
    command: |
      echo "VALUE OF VAR BEFORE "$var
      cd src/main/java/org/example
      javac HelloWorld.java
      echo "COMPILED SUCCESSFULLY"
      java HelloWorld
      var=22
      echo "VALUE OF VAR AFTER "$var
  
outputArtifacts:
  - name: outputEg3
    type: BINARY
    location: src/main/java/org/example/HelloWorld.class